[project]
name = "pyseed-examples"
version = "0.1.0"
description = "Example data and Python files for loading data into SEED through py-seed API"
readme = "README.md"
license = "BSD-4-Clause"
authors = [{ name = "Nicholas Long", email = "nicholas.long@nlr.gov" }]
requires-python = ">=3.10,<3.13"
dependencies = [
    "jupyterlab>=4.4,<5",
    "openpyxl>=3.1.5,<4",
    "pandas>=2.3,<3",
    "py-seed>=0.4.2",
    "usaddress>=0.5",
]

keywords = ["SEED Platform", "Building Benchmarking"]
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Developers",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
]

[project.urls]
Homepage = "https://seed-platform.org"
Documentation = "https://seed-platform.org"
Repository = "https://github.com/SEED-platform/pyseed-examples"

[dependency-groups]
dev = [
    "autopep8>=2.3.2",
    "flake8>=7.3.0",
    "mypy>=1.17.0",
    "pre-commit>=4.3.0",
    "pytest>=8.4.0",
    "pytest-cov>=6.2.0",
]

[tool.uv]
package = false
